import{a as w,S as b,i as a}from"./assets/vendor-5YrzWRhu.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&s(c)}).observe(document,{childList:!0,subtree:!0});function r(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(t){if(t.ep)return;t.ep=!0;const o=r(t);fetch(t.href,o)}})();const E="51535484-ce6dacd6a97960c9e0e55a6bc",S="https://pixabay.com/api/",v=15;async function f(e,n=1){const r={key:E,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:n,per_page:v};try{return(await w.get(S,{params:r})).data}catch(s){throw new Error("Failed to fetch images: "+s.message)}}const h=document.querySelector(".gallery");let q=new b(".gallery a");function m(){return document.querySelector(".loader")}function y(){const e=m();e&&e.classList.remove("hidden")}function g(){const e=m();e&&e.classList.add("hidden")}function P(){h.innerHTML=""}function p(e){const n=e.map(r=>`
      <li class="gallery-item">
        <a href="${r.largeImageURL}">
          <img src="${r.webformatURL}" alt="${r.tags}" />
        </a>
        <div class="info">
          <p>Likes: ${r.likes}</p>
          <p>Views: ${r.views}</p>
          <p>Comments: ${r.comments}</p>
          <p>Downloads: ${r.downloads}</p>
        </div>
      </li>`).join("");h.insertAdjacentHTML("beforeend",n),q.refresh()}function B(){const e=document.querySelector(".load-more");e&&e.classList.remove("hidden")}function l(){const e=document.querySelector(".load-more");e&&e.classList.add("hidden")}const u=document.querySelector(".form"),C=document.querySelector(".load-more");let i=1,d="",L=0;u.addEventListener("submit",async e=>{e.preventDefault();const n=u.querySelector('input[name="search-text"]');if(!n){a.error({title:"Error",message:"Search input not found in the form."});return}const r=n.value.trim();if(!r){a.warning({title:"Warning",message:"Please enter a search query!"});return}d=r,i=1,P(),l(),y();try{let t=function(){const o=document.querySelector(".gallery-item");if(o){const{height:c}=o.getBoundingClientRect();window.scrollBy({top:c*2,behavior:"smooth"})}};const s=await f(d,i);if(L=s.totalHits,!s.hits||s.hits.length===0){a.info({title:"No Results",message:"Sorry, there are no images matching your search query. Please try again!"});return}p(s.hits),s.totalHits>i*15?B():(l(),a.info({title:"End of Collection",message:"We're sorry, but you've reached the end of search results."}))}catch{a.error({title:"Error",message:"Failed to fetch images. Please try again later."})}finally{g()}});C.addEventListener("click",async()=>{i++,y();try{const e=await f(d,i);p(e.hits);const{height:n}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:n*2,behavior:"smooth"}),i*15>=L&&(l(),a.info({title:"End of Collection",message:"We're sorry, but you've reached the end of search results."}))}catch{a.error({title:"Error",message:"Failed to fetch images. Please try again later."})}finally{g()}});
//# sourceMappingURL=index.js.map
